language: php
php:
- 8.1
install:
- composer install --dev --no-interaction
script:
- vendor/bin/phpunit --version
- sh tests/run_tests.sh
after_script:
- php vendor/bin/coveralls -v
before_deploy:
- rm -f composer.phar README.md plugins.sqlite blacklist.txt .travis.yml manual_deploy.sh || (exit 0)
- rm -rf tests data || (exit 0)
- git commit -a --amend --no-edit || (exit 0)
